apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "kube-message"
  namespace: "kube-system"
  labels: 
    name: "kube-message"
spec: 
  replicas: 1
  selector: 
    matchLabels:
      name: "kube-message"
  template: 
    metadata: 
      labels: 
        name: "kube-message"
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
      - name: "rabbitmq"
        image: "rabbitmq:3.9.5-management"
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 15672  
        - containerPort: 5672  
        volumeMounts:
        - name: "rabbit-persistent-storage"
          mountPath: "/var/lib/rabbitmq"
      volumes: 
      - name: "rabbit-persistent-storage"
        hostPath:
          path: "/var/lib/doslab/rabbitmq"
---
apiVersion: v1
kind: Service
metadata:
  name: kube-message
  namespace: kube-system
  labels: 
    name: kube-message
spec:
  type: NodePort
  ports:
  - name: rabbitmq-management-port
    nodePort: 30305  
    port: 15672  
    protocol: TCP  
    targetPort: 15672  
  - name: rabbitmq-port 
    nodePort: 30304   
    port: 5672   
    protocol: TCP   
    targetPort: 5672
  selector:
    name: kube-message
