---
apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "kube-runtime-mirror"
  namespace: "kube-system"
  labels: 
    name: "kube-runtime-mirror"
spec: 
  replicas: 1
  selector: 
    matchLabels:
      name: "kube-runtime-mirror"
  template: 
    metadata: 
      labels: 
        name: "kube-runtime-mirror"
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
      - name: "kube-runtime-mirror"
        image: "registry.cn-beijing.aliyuncs.com/doslab/kube-runtime-mirror:v#version#"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: jdbcType
          value: "#type#"
        - name: jdbcHost
          value: "#host#"
        - name: jdbcPort
          value: "#port#"
        - name: kubeUrl
          value: "#url#"
        - name: kubeToken
          value: "#token#"
        - name: region
          value: #region#
        command: 
        - "java"
        - "-jar"
        - "kube-runtime-mirror.jar"
