---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: metadatas.doslab.io
spec:
  group: doslab.io
  names:
    kind: Metadata
    plural: metadatas
    shortNames:
    - metadata
    singular: metadata
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
            

